apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service # Replace with your application name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest # Replace with your Docker image name
          imagePullPolicy: Never # Change to Always if you are using a private registry
          envFrom:
            - secretRef:
                name: user-service-secret
          ports:
            - containerPort: 3000
              protocol: TCP
          #command: ['/bin/sh', '-c', 'env']
